
=pod

=encoding utf8

=head1 FORK

This is a fork of original [Virtualmin-Config](https://github.com/virtualmin/Virtualmin-Config) to be used specifically for [DOM Cloud](https://github.com/domcloud/container). Some patches might be useful to be pushed to upstream.

=head1 LICENSE AND COPYRIGHT

Licensed under the GPLv3. Copyright 2017 Virtualmin, Inc. <joe@virtualmin.com>

=cut
